-- =============================================
-- SPORTLINK DATABASE SCHEMA - DEFINITIVE VERSION
-- Data: 21/12/2025
-- Target: Supabase PostgreSQL 15+
-- Features: Full normalized structure + Security hardening + Performance optimization
-- =============================================

-- =============================================
-- 1. SETUP INIZIALE
-- =============================================
create extension if not exists "uuid-ossp";

-- =============================================
-- 2. TABELLE DIZIONARIO (LOOKUP TABLES)
-- =============================================

-- 2.1 RUOLI APPLICAZIONE (Le 7 Tipologie di Profilo)
create table public.lookup_roles (
  id text primary key,
  label text not null,
  description text,
  
  -- Capabilities (flags per funzionalità specifiche)
  is_medical boolean default false,
  can_create_club boolean default false,
  can_have_affiliations boolean default false,
  can_apply_to_opportunities boolean default false,
  can_be_club_member boolean default false,
  
  created_at timestamptz default now()
);

-- Popolamento Ruoli Iniziali
insert into public.lookup_roles (id, label, description, is_medical, can_create_club, can_have_affiliations, can_apply_to_opportunities, can_be_club_member) values 
('player', 'Giocatore', 'Cerca squadra, gestisci il tuo profilo e fatti notare.', false, false, true, true, true),
('coach', 'Allenatore', 'Cerca panchina e gestisci la tua carriera tecnica.', false, false, false, true, true),
('agent', 'Agente', 'Gestisci i tuoi assistiti e proponili ai club.', false, false, true, false, true),
('sporting_director', 'Direttore Sportivo', 'Crea la pagina del club e pubblica annunci.', false, true, false, false, true),
('athletic_trainer', 'Preparatore Atletico', 'Specialista nella preparazione fisica.', false, false, false, true, true),
('nutritionist', 'Nutrizionista', 'Specialista nell''alimentazione sportiva.', true, false, false, true, true),
('physio', 'Fisioterapista/Massaggiatore', 'Recupero infortuni e massaggi.', true, false, false, true, true);

-- 2.2 SPORT
create table public.lookup_sports (
  id bigint generated by default as identity primary key,
  name text unique not null,
  icon_url text,
  created_at timestamptz default now()
);

insert into public.lookup_sports (name) values ('Calcio'), ('Basket'), ('Volley');

-- 2.3 LIVELLI (Amateur, Pro, ecc)
create table public.lookup_levels (
  id bigint generated by default as identity primary key,
  name text not null,
  rank_order integer,
  created_at timestamptz default now()
);

-- 2.4 POSIZIONI SPECIFICHE (Dipendono da Sport e Ruolo)
create table public.lookup_positions (
  id bigint generated by default as identity primary key,
  sport_id bigint references public.lookup_sports(id) on delete cascade not null,
  role_id text references public.lookup_roles(id) on delete cascade not null,
  name text not null,
  category text,
  created_at timestamptz default now()
);

-- Esempio popolamento posizioni (Basket + Player)
insert into public.lookup_positions (sport_id, role_id, name) values 
(2, 'player', 'Playmaker'), 
(2, 'player', 'Guardia'), 
(2, 'player', 'Ala Piccola'), 
(2, 'player', 'Ala Grande'), 
(2, 'player', 'Centro');

-- =============================================
-- 3. UTENTI E PROFILI
-- =============================================

create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  
  -- Anagrafica
  first_name text not null,
  last_name text not null,
  username text unique,
  gender text check (gender in ('male', 'female', 'other', 'prefer_not_to_say')),
  
  -- Contatti (sincronizzati con auth.users via trigger)
  email text,
  phone_number text,
  
  -- Ruolo Applicativo (FK verso i 7 ruoli)
  role_id text references public.lookup_roles(id),
  
  -- Media & Info
  bio text,
  avatar_url text,
  cover_url text,
  city text,
  country text,
  birth_date date,
  
  -- Coordinate (Future Mappe)
  latitude double precision,
  longitude double precision,
  
  -- Privacy Settings (JSONB)
  privacy_settings jsonb default '{"messages": "everyone", "profile_visibility": "public"}'::jsonb,
  
  -- Stati
  is_verified boolean default false,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  -- CONSTRAINTS (Data Integrity)
  constraint check_birth_date_valid check (
    birth_date is null or (
      birth_date <= (current_date - interval '13 years') and 
      birth_date >= (current_date - interval '120 years')
    )
  ),
  constraint check_valid_coordinates check (
    (latitude is null and longitude is null) or
    (latitude between -90 and 90 and longitude between -180 and 180)
  ),
  constraint check_privacy_keys check (
    privacy_settings ?& array['messages', 'profile_visibility']
  ),
  constraint check_names_valid check (
    char_length(first_name) > 0 and char_length(last_name) > 0
  ), -- previene nome e cognome vuoti nel database
  constraint check_gender_required_for_athletes check (
    -- Player, Coach e ruoli sportivi DEVONO specificare M o F
    (role_id in ('player', 'coach') and gender in ('male', 'female'))
    or
    -- Altri ruoli possono avere qualsiasi valore o null
    (role_id not in ('player', 'coach'))
  )
);

-- 3.1 DATI FISICI (Opzionale, 1:1)
create table public.physical_stats (
  user_id uuid references public.profiles(id) on delete cascade primary key,
  height_cm integer,
  weight_kg integer,
  dominant_foot text,
  dominant_hand text,
  additional_metrics jsonb default '{}'::jsonb,
  updated_at timestamptz default now(),
  
  -- CONSTRAINTS
  constraint check_height_valid check (height_cm is null or (height_cm between 50 and 300)),
  constraint check_weight_valid check (weight_kg is null or (weight_kg between 20 and 300))
);

-- 3.2 SPORT PRATICATI DAL PROFILO (Many-to-Many)
create table public.profile_sports (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  sport_id bigint references public.lookup_sports(id) on delete cascade not null,
  
  -- Livello e Ruolo Primario per questo sport
  level_id bigint references public.lookup_levels(id),
  primary_position_id bigint references public.lookup_positions(id),
  
  is_main_sport boolean default false,
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  unique(user_id, sport_id)
);

-- 3.3 RUOLI SECONDARI (1:N su profile_sports)
create table public.profile_secondary_positions (
  id bigint generated by default as identity primary key,
  profile_sport_id bigint references public.profile_sports(id) on delete cascade not null,
  position_id bigint references public.lookup_positions(id) on delete cascade not null,
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  unique(profile_sport_id, position_id)
);

-- =============================================
-- 4. CLUBS E MEMBERSHIP
-- =============================================

create table public.clubs (
  id uuid default gen_random_uuid() primary key,
  owner_id uuid references public.profiles(id) on delete cascade not null,
  
  name text not null,
  description text,
  city text,
  logo_url text,
  cover_url text,
  website text,
  founded_year integer,
  
  -- Polisportive (Array di ID sport)
  sport_ids bigint[], 
  
  is_verified boolean default false,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  -- CONSTRAINTS
  constraint check_founded_year_valid check (
    founded_year is null or (founded_year between 1800 and extract(year from current_date))
  )
);

-- 4.1 TABELLA RICHIESTE ADESIONE CLUB 
create table public.club_join_requests (
  id uuid default gen_random_uuid() primary key,
  club_id uuid references public.clubs(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  -- Il ruolo che l'utente vorrebbe avere
  requested_role text check (requested_role in ('Admin', 'Staff', 'Player')),
  
  -- Opzionale: posizione specifica
  requested_position_id bigint references public.lookup_positions(id),
  
  message text,
  
  -- Gestione approvazione
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  responded_at timestamptz,
  responded_by uuid references public.profiles(id),
  
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  -- Vincolo: Non puoi mandare 2 richieste in sospeso allo stesso club
  unique(club_id, user_id, status)
);

create table public.club_memberships (
  id uuid default gen_random_uuid() primary key,
  club_id uuid references public.clubs(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  club_role text not null check (club_role in ('Admin', 'Staff', 'Player')),
  
  -- Permessi specifici (Array di stringhe in formato JSON)
  permissions jsonb default '[]'::jsonb, 
  
  position_id bigint references public.lookup_positions(id),
  joined_at timestamptz default now(),
  career_start_date date,
  left_at date,
  status text default 'active' check (status in ('active', 'past', 'suspended')),
  
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  unique(club_id, user_id, career_start_date)
);

-- =============================================
-- 5. MARKETPLACE (Annunci & Candidature)
-- =============================================

create table public.opportunities (
  id uuid default gen_random_uuid() primary key,
  club_id uuid references public.clubs(id) on delete cascade not null,
  created_by uuid references public.profiles(id) not null,
  
  title text not null,
  description text,
  
  -- Tassonomia
  sport_id bigint references public.lookup_sports(id) not null,
  role_id text references public.lookup_roles(id) not null,
  position_id bigint references public.lookup_positions(id),
  
  salary_range text,
  contract_type text,
  city text,
  location text,
  expiry_date date not null,
  
  status text default 'open' check (status in ('draft', 'open', 'closed', 'archived')),
  
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz,
  
  -- CONSTRAINTS
  constraint check_expiry_date_future check (expiry_date >= current_date)
);

create table public.applications (
  id uuid default gen_random_uuid() primary key,
  opportunity_id uuid references public.opportunities(id) on delete cascade not null,
  applicant_id uuid references public.profiles(id) on delete cascade not null,
  agent_id uuid references public.profiles(id),
  
  status text default 'pending' check (status in ('pending', 'viewed', 'accepted', 'rejected', 'withdrawn')),
  message text,
  
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz,
  
  unique(opportunity_id, applicant_id)
);

-- =============================================
-- 6. SOCIAL & INTERACTIONS
-- =============================================

create table public.follows (
  follower_id uuid references public.profiles(id) on delete cascade not null,
  following_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  primary key (follower_id, following_id),
  check (follower_id != following_id)
);

create table public.blocks (
  blocker_id uuid references public.profiles(id) on delete cascade not null,
  blocked_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  primary key (blocker_id, blocked_id),
  check (blocker_id != blocked_id)
);

create table public.affiliations (
  id uuid default gen_random_uuid() primary key,
  agent_id uuid references public.profiles(id) on delete cascade not null,
  player_id uuid references public.profiles(id) on delete cascade not null,
  
  status text default 'pending' check (status in ('pending', 'active', 'rejected', 'terminated')),
  start_date date,
  end_date date,
  
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  unique(agent_id, player_id)
);

create table public.messages (
  id uuid default gen_random_uuid() primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  is_read boolean default false,
  
  created_at timestamptz default now(),
  deleted_at timestamptz,
  
  -- CONSTRAINTS
  constraint check_content_not_empty check (char_length(content) > 0),
  constraint check_different_users check (sender_id != receiver_id)
);

create table public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  type text not null,
  title text,
  message text,
  metadata jsonb,
  is_read boolean default false,
  
  created_at timestamptz default now(),
  deleted_at timestamptz
);

-- =============================================
-- 7. INDICI PER PERFORMANCE
-- =============================================

-- Profiles
create index idx_profiles_role on public.profiles(role_id) where deleted_at is null;
create index idx_profiles_username on public.profiles(username) where deleted_at is null;
create index idx_profiles_email on public.profiles(email) where deleted_at is null;
create index idx_profiles_deleted_at on public.profiles(deleted_at);

-- Follows (Cruciale per social graph)
create index idx_follows_follower on public.follows(follower_id) where deleted_at is null;
create index idx_follows_following on public.follows(following_id) where deleted_at is null;

-- Messages (Query per chat room)
create index idx_messages_participants on public.messages(sender_id, receiver_id) where deleted_at is null;
create index idx_messages_created_at on public.messages(created_at desc) where deleted_at is null;

-- Notifications (Query "mie notifiche non lette")
create index idx_notifications_user_unread on public.notifications(user_id, is_read, created_at desc) where deleted_at is null;

-- Clubs
create index idx_clubs_owner on public.clubs(owner_id) where deleted_at is null;
create index idx_clubs_deleted_at on public.clubs(deleted_at);

-- Club Memberships
create index idx_club_memberships_club on public.club_memberships(club_id) where deleted_at is null;
create index idx_club_memberships_user on public.club_memberships(user_id) where deleted_at is null;

-- Opportunities
create index idx_opportunities_club on public.opportunities(club_id) where deleted_at is null;
create index idx_opportunities_status on public.opportunities(status) where deleted_at is null;
create index idx_opportunities_sport on public.opportunities(sport_id) where deleted_at is null;

-- Applications
create index idx_applications_opportunity on public.applications(opportunity_id) where deleted_at is null;
create index idx_applications_applicant on public.applications(applicant_id) where deleted_at is null;
create index idx_applications_agent on public.applications(agent_id) where deleted_at is null;

-- Affiliations
create index idx_affiliations_agent on public.affiliations(agent_id) where deleted_at is null;
create index idx_affiliations_player on public.affiliations(player_id) where deleted_at is null;

-- =============================================
-- 8. ROW LEVEL SECURITY (RLS)
-- =============================================

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.physical_stats enable row level security;
alter table public.profile_sports enable row level security;
alter table public.profile_secondary_positions enable row level security;
alter table public.clubs enable row level security;
alter table public.club_join_requests enable row level security;
alter table public.club_memberships enable row level security;
alter table public.opportunities enable row level security;
alter table public.applications enable row level security;
alter table public.follows enable row level security;
alter table public.blocks enable row level security;
alter table public.affiliations enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;

-- Profiles Policies
create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using (deleted_at is null);

create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Physical Stats Policies
create policy "Physical stats viewable by everyone"
  on public.physical_stats for select
  using (true);

create policy "Users can manage own physical stats"
  on public.physical_stats for all
  using (auth.uid() = user_id);

-- Messages Policies
create policy "Users can see their own messages"
  on public.messages for select
  using ((auth.uid() = sender_id or auth.uid() = receiver_id) and deleted_at is null);

create policy "Users can send messages"
  on public.messages for insert
  with check (auth.uid() = sender_id);

create policy "Users can delete own messages"
  on public.messages for update
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- Notifications Policies
create policy "Users can see own notifications"
  on public.notifications for select
  using (auth.uid() = user_id and deleted_at is null);

create policy "Users can update own notifications"
  on public.notifications for update
  using (auth.uid() = user_id);

-- Follows Policies
create policy "Follows are viewable by everyone"
  on public.follows for select
  using (deleted_at is null);

create policy "Users can follow others"
  on public.follows for insert
  with check (auth.uid() = follower_id);

create policy "Users can unfollow"
  on public.follows for delete
  using (auth.uid() = follower_id);

-- Clubs Policies
create policy "Clubs are viewable by everyone"
  on public.clubs for select
  using (deleted_at is null);

create policy "Users can create clubs"
  on public.clubs for insert
  with check (auth.uid() = owner_id);

create policy "Club owners can update their clubs"
  on public.clubs for update
  using (auth.uid() = owner_id);

-- Opportunities Policies
create policy "Opportunities are viewable by everyone"
  on public.opportunities for select
  using (deleted_at is null);

create policy "Club admins and staff can create opportunities"
  on public.opportunities for insert
  with check (
    exists (
      select 1 from public.club_memberships
      where club_id = opportunities.club_id
      and user_id = auth.uid()
      and club_role in ('Admin', 'Staff')
      and deleted_at is null
    )
  );

create policy "Opportunity creators can update"
  on public.opportunities for update
  using (auth.uid() = created_by);

-- Applications Policies
create policy "Users can view applications for their opportunities"
  on public.applications for select
  using (
    auth.uid() = applicant_id or
    exists (
      select 1 from public.opportunities
      where opportunities.id = applications.opportunity_id
      and opportunities.created_by = auth.uid()
    )
  );

create policy "Users can apply to opportunities"
  on public.applications for insert
  with check (auth.uid() = applicant_id);

create policy "Users can update own applications"
  on public.applications for update
  using (auth.uid() = applicant_id);

-- =============================================
-- 9. TRIGGER AUTOMATICI
-- =============================================

-- 9.1 Trigger per sincronizzare email e phone da auth.users a profiles
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, phone_number, first_name, last_name, role_id)
  values (
    new.id,
    new.email,
    new.phone,
    coalesce(nullif(trim(new.raw_user_meta_data->>'first_name'), ''), 'Nome'),
    coalesce(nullif(trim(new.raw_user_meta_data->>'last_name'), ''), 'Cognome'),
    coalesce(new.raw_user_meta_data->>'role', 'player')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 9.2 Trigger per aggiornare email e phone quando cambiano in auth.users
create or replace function public.handle_user_update()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  update public.profiles
  set 
    email = new.email,
    phone_number = new.phone,
    updated_at = now()
  where id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
  after update of email, phone on auth.users
  for each row execute function public.handle_user_update();

-- 9.3 Trigger per aggiornare updated_at automaticamente
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_profiles on public.profiles;
create trigger set_updated_at_profiles
  before update on public.profiles
  for each row execute function public.handle_updated_at();

drop trigger if exists set_updated_at_clubs on public.clubs;
create trigger set_updated_at_clubs
  before update on public.clubs
  for each row execute function public.handle_updated_at();

drop trigger if exists set_updated_at_opportunities on public.opportunities;
create trigger set_updated_at_opportunities
  before update on public.opportunities
  for each row execute function public.handle_updated_at();

drop trigger if exists set_updated_at_applications on public.applications;
create trigger set_updated_at_applications
  before update on public.applications
  for each row execute function public.handle_updated_at();

-- =============================================
-- 10. VISTE DI UTILITÀ
-- =============================================

-- Vista statistiche profili (con filtro soft delete)
create or replace view public.profile_stats as
select 
  p.id as profile_id,
  p.username,
  p.first_name,
  p.last_name,
  -- Conta Followers
  (select count(*) from public.follows where following_id = p.id and deleted_at is null) as followers_count,
  -- Conta Following
  (select count(*) from public.follows where follower_id = p.id and deleted_at is null) as following_count,
  -- Conta Annunci Attivi
  (select count(*) from public.opportunities where created_by = p.id and status = 'open' and deleted_at is null) as active_opportunities_count,
  -- Conta Candidature Ricevute
  (select count(*) from public.applications a 
   join public.opportunities o on a.opportunity_id = o.id 
   where o.created_by = p.id and a.deleted_at is null) as applications_received_count,
  -- Conta Club di cui è membro
  (select count(*) from public.club_memberships where user_id = p.id and status = 'active' and deleted_at is null) as clubs_count
from public.profiles p
where p.deleted_at is null;

-- Vista conversazioni messaggi (ultimi messaggi per utente)
create or replace view public.conversations as
select distinct on (least(sender_id, receiver_id), greatest(sender_id, receiver_id))
  m.id,
  m.sender_id,
  m.receiver_id,
  m.content as last_message,
  m.is_read,
  m.created_at as last_message_at,
  case 
    when m.sender_id = auth.uid() then m.receiver_id
    else m.sender_id
  end as peer_id
from public.messages m
where m.deleted_at is null
  and (m.sender_id = auth.uid() or m.receiver_id = auth.uid())
order by 
  least(sender_id, receiver_id), 
  greatest(sender_id, receiver_id),
  m.created_at desc;

-- =============================================
-- FINE SCHEMA
-- =============================================

-- Commenti finali:
comment on table public.profiles is 'Profili utenti con sincronizzazione email/phone da auth.users';
comment on table public.opportunities is 'Annunci di lavoro pubblicati dai club';
comment on table public.applications is 'Candidature degli utenti agli annunci';
comment on table public.affiliations is 'Relazioni agente-giocatore';
comment on table public.club_memberships is 'Membri dei club con ruoli e permessi';
