-- =============================================
-- DB SCHEMA - SPORTS PLATFORM (v1.0)
-- Data: 15/12/2025
-- =============================================

-- 1. SETUP INIZIALE
create extension if not exists "uuid-ossp";

-- =============================================
-- 2. TABELLE DIZIONARIO (LOOKUP TABLES)
-- =============================================

-- 2.1 RUOLI APPLICAZIONE (Le 7 Tipologie di Profilo)
create table public.lookup_roles (
  id text primary key, -- 'player', 'agent', etc.
  label text not null, -- 'Giocatore', 'Agente'
  description text, 
  is_medical boolean default false,
  can_create_club boolean default false
);

-- Popolamento Ruoli Iniziali
insert into public.lookup_roles (id, label, description, is_medical, can_create_club) values 
('player', 'Giocatore', 'Cerca squadra, gestisci il tuo profilo e fatti notare.', false, false),
('coach', 'Allenatore', 'Cerca panchina e gestisci la tua carriera tecnica.', false, false),
('agent', 'Agente', 'Gestisci i tuoi assistiti e proponili ai club.', false, false),
('sporting_director', 'Direttore Sportivo', 'Crea la pagina del club e pubblica annunci.', false, true),
('athletic_trainer', 'Preparatore Atletico', 'Specialista nella preparazione fisica.', false, false),
('nutritionist', 'Nutrizionista', 'Specialista nell''alimentazione sportiva.', true, false),
('physio', 'Fisioterapista/Massaggiatore', 'Recupero infortuni e massaggi.', true, false);

-- 2.2 SPORT
create table public.lookup_sports (
  id bigint generated by default as identity primary key,
  name text unique not null,
  icon_url text
);

insert into public.lookup_sports (name) values ('Calcio'), ('Basket'), ('Volley');

-- 2.3 LIVELLI (Amateur, Pro, ecc)
create table public.lookup_levels (
  id bigint generated by default as identity primary key,
  name text not null,
  rank_order integer
);

-- 2.4 POSIZIONI SPECIFICHE (Dipendono da Sport e Ruolo)
create table public.lookup_positions (
  id bigint generated by default as identity primary key,
  sport_id bigint references public.lookup_sports(id) on delete cascade not null,
  role_id text references public.lookup_roles(id) on delete cascade not null,
  name text not null,
  category text
);

-- Esempio popolamento posizioni (Basket + Player)
insert into public.lookup_positions (sport_id, role_id, name) values 
(2, 'player', 'Playmaker'), (2, 'player', 'Guardia'), (2, 'player', 'Ala Piccola'), (2, 'player', 'Ala Grande'), (2, 'player', 'Centro');

-- =============================================
-- 3. UTENTI E PROFILI
-- =============================================

create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  
  -- Anagrafica
  first_name text,
  last_name text,
  username text unique,
  email text,
  
  -- Ruolo Applicativo (FK verso i 7 ruoli)
  role_id text references public.lookup_roles(id),
  
  -- Media & Info
  bio text,
  avatar_url text,
  cover_url text,
  city text,
  country text,
  birth_date date,
  
  -- Coordinate (Future Mappe)
  latitude float,
  longitude float,
  
  -- Privacy Settings (JSONB)
  privacy_settings jsonb default '{"messages": "everyone", "profile_visibility": "public"}'::jsonb,
  
  -- Stati
  is_verified boolean default false,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3.1 DATI FISICI (Opzionale, 1:1)
create table public.physical_stats (
  user_id uuid references public.profiles(id) on delete cascade primary key,
  height_cm integer,
  weight_kg integer,
  dominant_foot text,
  dominant_hand text,
  additional_metrics jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

-- 3.2 SPORT PRATICATI DAL PROFILO (Many-to-Many)
create table public.profile_sports (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  sport_id bigint references public.lookup_sports(id) on delete cascade not null,
  
  -- Livello e Ruolo Primario per questo sport
  level_id bigint references public.lookup_levels(id),
  primary_position_id bigint references public.lookup_positions(id),
  
  is_main_sport boolean default false,
  unique(user_id, sport_id)
);

-- 3.3 RUOLI SECONDARI (1:N su profile_sports)
create table public.profile_secondary_positions (
  id bigint generated by default as identity primary key,
  profile_sport_id bigint references public.profile_sports(id) on delete cascade not null,
  position_id bigint references public.lookup_positions(id) on delete cascade not null,
  unique(profile_sport_id, position_id)
);

-- =============================================
-- 4. CLUBS E MEMBERSHIP
-- =============================================

create table public.clubs (
  id uuid default gen_random_uuid() primary key,
  owner_id uuid references public.profiles(id) on delete cascade not null,
  
  name text not null,
  description text,
  city text,
  logo_url text,
  cover_url text,
  website text,
  founded_year integer,
  
  -- Polisportive (Array di ID sport)
  sport_ids bigint[], 
  
  is_verified boolean default false,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4.X TABELLA RICHIESTE ADESIONE CLUB 
create table public.club_join_requests (
  id uuid default gen_random_uuid() primary key,
  club_id uuid references public.clubs(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  -- Il ruolo che l'utente vorrebbe avere (es. "Voglio entrare come Player")
  requested_role text check (requested_role in ('Admin', 'Staff', 'Player')),
  
  -- Opzionale: Se vuole candidarsi per una posizione specifica (es. "Portiere")
  requested_position_id bigint references public.lookup_positions(id),
  
  message text, -- "Ciao, sono bravo, fatemi entrare"
  
  -- Gestione approvazione
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  responded_at timestamptz,
  responded_by uuid references public.profiles(id), -- L'admin che ha accettato/rifiutato
  
  created_at timestamptz default now(),
  
  -- Vincolo: Non puoi mandare 2 richieste in sospeso allo stesso club
  unique(club_id, user_id, status)
);

create table public.club_memberships (
  id uuid default gen_random_uuid() primary key,
  club_id uuid references public.clubs(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  club_role text not null check (club_role in ('Admin', 'Staff', 'Player')),
  
  -- NUOVO CAMPO: Permessi specifici (Array di stringhe in formato JSON)
  -- Es: ["create_opportunities", "manage_members"]
  permissions jsonb default '[]'::jsonb, 
  
  position_id bigint references public.lookup_positions(id),
  joined_at timestamptz default now(),
  career_start_date date,
  left_at date,
  status text default 'active' check (status in ('active', 'past', 'suspended')),
  created_at timestamptz default now(),
  unique(club_id, user_id, career_start_date)
);


-- =============================================
-- 5. MARKETPLACE (Annunci & Candidature)
-- =============================================

create table public.opportunities (
  id uuid default gen_random_uuid() primary key,
  club_id uuid references public.clubs(id) on delete cascade not null,
  created_by uuid references public.profiles(id) not null,
  
  title text not null,
  description text,
  
  -- Tassonomia
  sport_id bigint references public.lookup_sports(id) not null,
  role_id text references public.lookup_roles(id) not null, -- Es. Cerco 'player'
  position_id bigint references public.lookup_positions(id), -- Es. Cerco 'Playmaker'
  
  salary_range text,
  contract_type text,
  city text,
  location text,
  expiry_date date not null,
  
  status text default 'open' check (status in ('draft', 'open', 'closed', 'archived')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.applications (
  id uuid default gen_random_uuid() primary key,
  opportunity_id uuid references public.opportunities(id) on delete cascade not null,
  applicant_id uuid references public.profiles(id) on delete cascade not null,
  agent_id uuid references public.profiles(id),
  
  status text default 'pending' check (status in ('pending', 'viewed', 'accepted', 'rejected', 'withdrawn')),
  message text,
  
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(opportunity_id, applicant_id)
);

-- =============================================
-- 6. SOCIAL & INTERACTIONS
-- =============================================

create table public.follows (
  follower_id uuid references public.profiles(id) on delete cascade not null,
  following_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  primary key (follower_id, following_id),
  check (follower_id != following_id)
);

create table public.blocks (
  blocker_id uuid references public.profiles(id) on delete cascade not null,
  blocked_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  primary key (blocker_id, blocked_id)
);

create table public.affiliations (
  id uuid default gen_random_uuid() primary key,
  agent_id uuid references public.profiles(id) on delete cascade not null,
  player_id uuid references public.profiles(id) on delete cascade not null,
  
  status text default 'pending' check (status in ('pending', 'active', 'rejected', 'terminated')),
  start_date date,
  end_date date,
  created_at timestamptz default now(),
  
  unique(agent_id, player_id)
);

create table public.messages (
  id uuid default gen_random_uuid() primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);

create table public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  type text not null,
  title text,
  message text,
  metadata jsonb,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- =============================================
-- 7. TRIGGER AUTOMATICI
-- =============================================
-- Creazione automatica profilo alla registrazione utente
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, first_name, last_name)
  values (new.id, new.email, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 8. VISTA STATISTICHE UTENTE (Sostituisce annunciAttivi, followers, ecc.)
-- Questa è una "tabella virtuale". Quando la interroghi, calcola i dati live.
create or replace view public.profile_stats as
select 
  p.id as profile_id,
  -- Conta Followers
  (select count(*) from public.follows where following_id = p.id) as followers_count,
  -- Conta Following
  (select count(*) from public.follows where follower_id = p.id) as following_count,
  -- Conta Annunci Attivi
  (select count(*) from public.opportunities where created_by = p.id and status = 'open') as active_opportunities_count,
  -- Conta Candidature Ricevute (Totale su tutti i suoi annunci)
  (select count(*) from public.applications a 
   join public.opportunities o on a.opportunity_id = o.id 
   where o.created_by = p.id) as applications_received_count
from public.profiles p;

-- ESEMPIO DI USO NEL CODICE:
-- supabase.from('profile_stats').select('*').eq('profile_id', '123...')