-- Migration: crea la tabella club_sports (relazione N:N tra clubs e lookup_sports)
-- Sostituisce il campo sport_ids[] su clubs che non viene usato correttamente

-- 1. Tabella join club_sports
CREATE TABLE IF NOT EXISTS public.club_sports (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     uuid NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
    sport_id    bigint NOT NULL REFERENCES public.lookup_sports(id) ON DELETE CASCADE,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_club_sport UNIQUE (club_id, sport_id)
);

CREATE INDEX IF NOT EXISTS idx_club_sports_club ON public.club_sports (club_id);
CREATE INDEX IF NOT EXISTS idx_club_sports_sport ON public.club_sports (sport_id);

-- 2. RLS
ALTER TABLE public.club_sports ENABLE ROW LEVEL SECURITY;

-- Chiunque può leggere
DROP POLICY IF EXISTS "Public can view club sports" ON public.club_sports;
CREATE POLICY "Public can view club sports"
    ON public.club_sports FOR SELECT
    TO public
    USING (true);

-- Solo l'Admin del club può inserire/aggiornare/eliminare gli sport del suo club
DROP POLICY IF EXISTS "Authenticated can manage club sports" ON public.club_sports;

-- INSERT: solo se sei Admin attivo di quel club
DROP POLICY IF EXISTS "Club admin can insert club sports" ON public.club_sports;
CREATE POLICY "Club admin can insert club sports"
    ON public.club_sports FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.club_memberships cm
            WHERE cm.club_id  = club_sports.club_id
              AND cm.user_id  = auth.uid()
              AND cm.club_role = 'Admin'
              AND cm.status   = 'active'
        )
    );

-- UPDATE: solo se sei Admin attivo di quel club
DROP POLICY IF EXISTS "Club admin can update club sports" ON public.club_sports;
CREATE POLICY "Club admin can update club sports"
    ON public.club_sports FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.club_memberships cm
            WHERE cm.club_id  = club_sports.club_id
              AND cm.user_id  = auth.uid()
              AND cm.club_role = 'Admin'
              AND cm.status   = 'active'
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.club_memberships cm
            WHERE cm.club_id  = club_sports.club_id
              AND cm.user_id  = auth.uid()
              AND cm.club_role = 'Admin'
              AND cm.status   = 'active'
        )
    );

-- DELETE: solo se sei Admin attivo di quel club
DROP POLICY IF EXISTS "Club admin can delete club sports" ON public.club_sports;
CREATE POLICY "Club admin can delete club sports"
    ON public.club_sports FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.club_memberships cm
            WHERE cm.club_id  = club_sports.club_id
              AND cm.user_id  = auth.uid()
              AND cm.club_role = 'Admin'
              AND cm.status   = 'active'
        )
    );
